// type of pokemon
export enum EPokemonType {
	NORMAL = 'normal',
	FIRE = 'fire',
	WATER = 'water',
	GRASS = 'grass',
	ELECTRIC = 'electric',
	ICE = 'ice',
	FIGHTING = 'fighting',
	POISON = 'poison',
	GROUND = 'ground',
	FLYING = 'flying',
	PSYCHIC = 'psychic',
	BUG = 'bug',
	ROCK = 'rock',
	GHOST = 'ghost',
	DARK = 'dark',
	DRAGON = 'dragon',
	STEEL = 'steel',
	FAIRY = 'fairy',
};

export const POKEMON_TYPE_ATTRS = [
	EPokemonType.BUG,
	EPokemonType.DARK,
	EPokemonType.DRAGON,
	EPokemonType.ELECTRIC,
	EPokemonType.FAIRY,
	EPokemonType.FIGHTING,
	EPokemonType.FIRE,
	EPokemonType.GHOST,
	EPokemonType.GRASS,
	EPokemonType.GROUND,
	EPokemonType.ICE,
	EPokemonType.NORMAL,
	EPokemonType.POISON,
	EPokemonType.PSYCHIC,
	EPokemonType.ROCK,
	EPokemonType.STEEL,
	EPokemonType.WATER,
	EPokemonType.FLYING,
]